# Generated by Django 3.0.8 on 2020-12-18 11:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=7)),
                ('label', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('checked', models.BooleanField(default=False)),
                ('dueDate', models.DateTimeField(blank=True, null=True)),
                ('tag', models.ForeignKey(default=uuid.UUID('80596133-b5e2-479c-91f5-3423a10ceab2'), on_delete=django.db.models.deletion.SET_DEFAULT, to='todo.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('dueDate', models.DateTimeField(blank=True, null=True)),
                ('checked', models.BooleanField(default=False)),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='todo.Todo')),
            ],
        ),
    ]
