# Generated by Django 3.0.8 on 2020-12-18 11:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='tag',
            field=models.ForeignKey(default=uuid.UUID('ab4f01bc-dfaa-4442-81cc-ff40bab697f6'), on_delete=django.db.models.deletion.SET_DEFAULT, to='todo.Tag'),
        ),
    ]
