# Generated by Django 3.0.8 on 2020-12-18 11:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20201218_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='tag',
            field=models.ForeignKey(default=uuid.UUID('091ea521-de1e-4fb0-bdc0-61377acd13b6'), on_delete=django.db.models.deletion.SET_DEFAULT, to='todo.Tag'),
        ),
    ]
