# Generated by Django 3.0.8 on 2020-12-18 11:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20201218_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='tag',
            field=models.ForeignKey(default=uuid.UUID('5466ea46-950b-4a53-b655-3f51b65edd2f'), on_delete=django.db.models.deletion.SET_DEFAULT, to='todo.Tag'),
        ),
    ]
