# Generated by Django 3.0.8 on 2020-12-18 11:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20201218_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='tag',
            field=models.ForeignKey(default=uuid.UUID('f84ff798-d7db-4fa1-9f1f-ece72f553006'), on_delete=django.db.models.deletion.SET_DEFAULT, to='todo.Tag'),
        ),
    ]
