# Generated by Django 3.0.8 on 2021-01-01 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_todo_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
