# Generated by Django 3.0.8 on 2021-02-03 13:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0015_auto_20210126_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='PomodoroInterval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('defaultDuration', models.DurationField()),
                ('todo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intervals', to='todo.Todo')),
            ],
        ),
    ]
