# Generated by Django 3.0.8 on 2021-02-22 05:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0024_auto_20210222_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
