# Generated by Django 3.0.8 on 2021-03-11 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0025_auto_20210222_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
