# Generated by Django 3.0.8 on 2021-03-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0026_auto_20210311_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
