# Generated by Django 3.0.8 on 2021-03-27 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0028_auto_20210317_0026'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('user', 'label'), name='unique_tag_title'),
        ),
    ]
